version: "3.5"

services:
  web:
    build:
      context: .
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    volumes:
      - .:/deploy/app
    ports:
      - "8000:8000"
